### PR TITLE
improve readability

### PR DESCRIPTION
**Pull request by akantsevoi**

### CODE REVIEW

**Review by dkorolev — COMMENTED** [review]
Do we need this though? Does it not highlight the syntax well without it?

**Comment by akantsevoi** [comment]
Yep. Without highlight:

image

and with highlight:

image

**Comment by dkorolev** [comment]
Sweet! Already merged as part of your other PR, right?

**Comment by akantsevoi** [comment]
Yep. made a branch and PR, than from that branch I made another branch and the second PR, so there will be no merge conflicts. But maybe I did smth wrong.

Anyway, everything is good now

**Pull request merged**
